// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAThzMr6A-Z-Q3-jJj6LaWEwGYj7v0EzMQ',
    appId: '1:882626851590:web:7300539af44d7f93a5e487',
    messagingSenderId: '882626851590',
    projectId: 'pizza-app-7cb77',
    authDomain: 'pizza-app-7cb77.firebaseapp.com',
    storageBucket: 'pizza-app-7cb77.firebasestorage.app',
    measurementId: 'G-QCYCJLXLSJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKvaPUG7vvVVynTTBiw-jMzPxaD7CwuGo',
    appId: '1:882626851590:android:5451f6fd1d03939ba5e487',
    messagingSenderId: '882626851590',
    projectId: 'pizza-app-7cb77',
    storageBucket: 'pizza-app-7cb77.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCA0r1X7ItF-sxtSXsiFkmBFjj5iqXIjv8',
    appId: '1:882626851590:ios:05fbb193fbe7dfaba5e487',
    messagingSenderId: '882626851590',
    projectId: 'pizza-app-7cb77',
    storageBucket: 'pizza-app-7cb77.firebasestorage.app',
    iosBundleId: 'com.example.pizzaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCA0r1X7ItF-sxtSXsiFkmBFjj5iqXIjv8',
    appId: '1:882626851590:ios:05fbb193fbe7dfaba5e487',
    messagingSenderId: '882626851590',
    projectId: 'pizza-app-7cb77',
    storageBucket: 'pizza-app-7cb77.firebasestorage.app',
    iosBundleId: 'com.example.pizzaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAThzMr6A-Z-Q3-jJj6LaWEwGYj7v0EzMQ',
    appId: '1:882626851590:web:28c9aca3fd6eb1fba5e487',
    messagingSenderId: '882626851590',
    projectId: 'pizza-app-7cb77',
    authDomain: 'pizza-app-7cb77.firebaseapp.com',
    storageBucket: 'pizza-app-7cb77.firebasestorage.app',
    measurementId: 'G-69MGNSMESX',
  );
}
